language: cpp
compiler: g++
dist: trusty

cache:
  pip: true
  directories:
  - /home/travis/.conan

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

  - mkdir cmake
  - pushd cmake
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
  - chmod +x cmake-*-Linux-x86_64.sh
  - ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
  - export PATH="${PWD}/bin:$PATH"
  - popd

  - pip install 'requests[security]'
  - pip install --user conan

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libglew-dev
      - libsndfile1-dev
      - libopenal-dev
      - libfreetype6-dev
      - libx11-xcb-dev
      - udev
      - libudev-dev
      - libxcb-image0
      - libxcb-image0-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make